const ROUTE_LIST = {
  HOME: 'HOME',
  MAIN: 'MAIN',
  JOURNAL: 'JOURNAL',
  DISCOVER: 'DISCOVER',
  STATS: 'STATS',
  SETTINGS: 'SETTINGS',
  JOURNAL_ENTRY: 'JOURNAL_ENTRY',
};

export default ROUTE_LIST;
