export const APP_TEXT_FONT_SIZE_LIST = {
    H1_FONT_SIZE : 28,
    H2_FONT_SIZE : 24,
    H3_FONT_SIZE : 20,
    NORMAL_FONT_SIZE : 16,
    SMALL_FONT_SIZE : 14,
}

export const APP_TEXT_COLOR_LIST = {
    H1_COLOR: '#32828D',
    H2_COLOR: '#EBEBEB',
    H3_COLOR: '#3994A0',
    NORMAL_COLOR: '#EBEBEB',
    SMALL_COLOR: '#EBEBEB'
}